name: CI Test 
# github.event_name ?
run-name: ${{ github.actor }} did ${{ github.event_name }} test
## Workflow (CI) trigger 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

## Jobs
jobs:
  flip-test:
    runs-on: ubuntu-slim 
    ## Matrix Strategie: Test on mulitple node versions
    strategy:
      matrix:
        node-version: [18, 20, '22.17.0']
      fail-fast: false # if one fails, the others continue
    name: Tests Nodejs server ${{ matrix.node-version }}
    steps:
      - name: Checkout clone # clones repo
        uses: actions/checkout@v6
      
      - name: Install node # installs node
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
          cache-dependency-path: '**/package.json'

      - name: Install node modules # npm ci
        run: npm install
      
      - name: Start testing :)
        run: npm run test